version: "3.7"

networks:
    docker.network:
        driver: bridge

services:
    web:
        build: .
        container_name: web
        depends_on:
            - db
        ports:
            - "${APACHE_PORT}:80"
        networks:
            - docker.network
        volumes:
            - ./docker/logs:/var/log/httpd
            - .:/var/www/html
    db:
        image: mysql
        container_name: db
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - docker.network
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
